# picks/management/commands/load_schedule.py
from django.core.management.base import BaseCommand
from picks.models import Game

SCHEDULE = {
    'Alabama': {
        'Week 1': 'Florida State',
        'Week 2': 'UL-Monroe',
        'Week 3': 'Wisconsin',
        'Week 4': None,
        'Week 5': 'Georgia',
        'Week 6': 'Vanderbilt',
        'Week 7': 'Missouri',
        'Week 8': 'Tennessee',
        'Week 9': 'South Carolina',
        'Week 10': None,
        'Week 11': 'LSU',
        'Week 12': 'Oklahoma',
        'Week 13': 'Eastern Illinois',
        'Week 14': 'Auburn'
    },
    'Arkansas': {
        'Week 1': 'Alabama A&M',
        'Week 2': 'Arkansas State',
        'Week 3': 'Ole Miss',
        'Week 4': 'Memphis',
        'Week 5': 'Notre Dame',
        'Week 6': None,
        'Week 7': 'Tennessee',
        'Week 8': 'Texas A&M',
        'Week 9': 'Auburn',
        'Week 10': 'Mississippi State',
        'Week 11': None,
        'Week 12': 'LSU',
        'Week 13': 'Texas',
        'Week 14': 'Missouri'
    },
    'Auburn': {
        'Week 1': 'Baylor',
        'Week 2': 'Ball State',
        'Week 3': 'South Alabama',
        'Week 4': 'Oklahoma',
        'Week 5': 'Texas A&M',
        'Week 6': None,
        'Week 7': 'Georgia',
        'Week 8': 'Missouri',
        'Week 9': None,
        'Week 10': 'Kentucky',
        'Week 11': 'Vanderbilt',
        'Week 12': None,
        'Week 13': 'Mercer',
        'Week 14': None
    },
    'Florida': {
        'Week 1': 'Long Island',
        'Week 2': 'South Florida',
        'Week 3': 'LSU',
        'Week 4': 'Miami',
        'Week 5': None,
        'Week 6': 'Texas',
        'Week 7': 'Texas A&M',
        'Week 8': 'Mississippi State',
        'Week 9': None,
        'Week 10': 'Georgia',
        'Week 11': 'Kentucky',
        'Week 12': 'Ole Miss',
        'Week 13': 'Tennessee',
        'Week 14': 'Florida State'
    },
    'Georgia': {
        'Week 1': 'Marshall',
        'Week 2': 'Austin Peay',
        'Week 3': 'Tennessee',
        'Week 4': None,
        'Week 5': None,
        'Week 6': 'Kentucky',
        'Week 7': None,
        'Week 8': 'Ole Miss',
        'Week 9': None,
        'Week 10': None,
        'Week 11': 'Mississippi State',
        'Week 12': 'Texas',
        'Week 13': 'Charlotte',
        'Week 14': 'Georgia Tech'
    },
    'Kentucky': {
        'Week 1': 'Toledo',
        'Week 2': 'Ole Miss',
        'Week 3': 'Eastern Michigan',
        'Week 4': None,
        'Week 5': 'South Carolina',
        'Week 6': None,
        'Week 7': None,
        'Week 8': 'Texas',
        'Week 9': 'Tennessee',
        'Week 10': None,
        'Week 11': None,
        'Week 12': 'Tennessee Tech',
        'Week 13': 'Vanderbilt',
        'Week 14': 'Louisville'
    },
    'LSU': {
        'Week 1': 'Clemson',
        'Week 2': 'Louisiana Tech',
        'Week 3': None,
        'Week 4': 'Southeastern Louisiana',
        'Week 5': 'Ole Miss',
        'Week 6': None,
        'Week 7': 'South Carolina',
        'Week 8': 'Vanderbilt',
        'Week 9': "Texas A&M",
        'Week 10': None,
        'Week 11': None,
        'Week 12': None,
        'Week 13': 'Western Kentucky',
        'Week 14': 'Oklahoma'
    },
    'Ole Miss': {
        'Week 1': 'Georgia State',
        'Week 2': None,
        'Week 3': None,
        'Week 4': 'Tulane',
        'Week 5': None,
        'Week 6': None,
        'Week 7': 'Washington State',
        'Week 8': None,
        'Week 9': 'Oklahoma',
        'Week 10': 'South Carolina',
        'Week 11': 'The Citadel',
        'Week 12': None,
        'Week 13': None,
        'Week 14': 'Mississippi State'
    },
    'Mississippi State': {
        'Week 1': 'Southern Miss',
        'Week 2': 'Arizona State',
        'Week 3': 'Alcorn State',
        'Week 4': 'Northern Illinois',
        'Week 5': 'Tennessee',
        'Week 6': 'Texas A&M',
        'Week 7': None,
        'Week 8': None,
        'Week 9': 'Texas',
        'Week 10': None,
        'Week 11': None,
        'Week 12': 'Missouri',
        'Week 13': None,
        'Week 14': None
    },
    'Missouri': {
        'Week 1': 'Central Arkansas',
        'Week 2': 'Kansas',
        'Week 3': 'UL-Lafayette',
        'Week 4': 'South Carolina',
        'Week 5': 'UMass',
        'Week 6': None,
        'Week 7': None,
        'Week 8': None,
        'Week 9': 'Vanderbilt',
        'Week 10': None,
        'Week 11': 'Texas A&M',
        'Week 12': None,
        'Week 13': 'Oklahoma',
        'Week 14': None
    },
    'Oklahoma': {
        'Week 1': 'Illinois State',
        'Week 2': 'Michigan',
        'Week 3': 'Temple',
        'Week 4': None,
        'Week 5': None,
        'Week 6': 'Kent State',
        'Week 7': 'Texas',
        'Week 8': 'South Carolina',
        'Week 9': None,
        'Week 10': 'Tennessee',
        'Week 11': None,
        'Week 12': None,
        'Week 13': None,
        'Week 14': None
    },

    'South Carolina': {
        'Week 1': 'Virginia Tech',
        'Week 2': 'South Carolina State',
        'Week 3': 'Vanderbilt',
        'Week 4': None,
        'Week 5': None,
        'Week 6': None,
        'Week 7': None,
        'Week 8': None,
        'Week 9': None,
        'Week 10': None,
        'Week 11': None,
        'Week 12': 'Texas A&M',
        'Week 13': 'Coastal Carolina',
        'Week 14': 'Clemson'
    },
    'Tennessee': {
        'Week 1': 'Syracuse',
        'Week 2': 'East Tennessee State',
        'Week 3': None,
        'Week 4': 'UAB',
        'Week 5': None,
        'Week 6': None,
        'Week 7': None,
        'Week 8': None,
        'Week 9': None,
        'Week 10': None,
        'Week 11': None,
        'Week 12': 'New Mexico State',
        'Week 13': None,
        'Week 14': 'Vanderbilt'
    },
    'Texas': {
        'Week 1': 'Ohio State',
        'Week 2': 'San Jose State',
        'Week 3': 'UTEP',
        'Week 4': None,
        'Week 5': 'Sam Houston',
        'Week 6': None,
        'Week 7': None,
        'Week 8': None,
        'Week 9': None,
        'Week 10': 'Vanderbilt',
        'Week 11': None,
        'Week 12': None,
        'Week 13': None,
        'Week 14': 'Texas A&M'
    },
    'Texas A&M': {
        'Week 1': 'UTSA',
        'Week 2': 'Utah State',
        'Week 3': 'Notre Dame',
        'Week 4': None,
        'Week 5': None,
        'Week 6': None,
        'Week 7': None,
        'Week 8': None,
        'Week 9': None,
        'Week 10': None,
        'Week 11': None,
        'Week 12': None,
        'Week 13': 'Samford',
        'Week 14': None
    },
    'Vanderbilt': {
        'Week 1': 'Charleston Southern',
        'Week 2': 'Virginia Tech',
        'Week 3': None,
        'Week 4': 'Georgia State',
        'Week 5': 'Utah State',
        'Week 6': None,
        'Week 7': None,
        'Week 8': None,
        'Week 9': None,
        'Week 10': None,
        'Week 11': None,
        'Week 12': None,
        'Week 13': None,
        'Week 14': None
    },
}

class Command(BaseCommand):
    help = "Load the football schedule into the database using week numbers"

    def handle(self, *args, **options):
        # Clear existing games
        Game.objects.all().delete()
        for team, weeks in SCHEDULE.items():
            for week, opponent in weeks.items():
                if opponent:  # Only create a game record if an opponent is provided.
                    Game.objects.create(team=team, week=week, opponent=opponent)
        self.stdout.write(self.style.SUCCESS("Schedule loaded successfully."))
