# Generated by Django 4.2.18 on 2025-02-10 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("picks", "0002_game_is_home"),
    ]

    operations = [
        migrations.RenameField(model_name="game", old_name="date", new_name="week",),
        migrations.RemoveField(model_name="game", name="is_home",),
    ]
