# Generated by Django 4.2.18 on 2025-02-10 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("picks", "0003_rename_date_game_week_remove_game_is_home"),
    ]

    operations = [
        migrations.AlterModelManagers(name="user", managers=[],),
    ]
